import { ObserverPatternDemo } from './observer';
import { FactoryPatternDemo } from './factory';
import { PrototypePatternDemo } from './prototype';
import { DecoratorPatternDemo } from './decorator';
import { FacadePatternDemo } from './facade';
import { BridgePatternDemo } from './bridge';
import { AdapterPatternDemo } from './adapter';
import { AdapterPatternDemo2 } from './adapter2';
import { CompositePatternDemo } from './composite';
import { SingletonPatternDemo } from './singleton';

//ObserverPatternDemo();
//FactoryPatternDemo();
//PrototypePatternDemo();
//DecoratorPatternDemo();
//FacadePatternDemo();
//BridgePatternDemo();
//AdapterPatternDemo();
//AdapterPatternDemo2();
//CompositePatternDemo();
//CompositePatternDemo();
SingletonPatternDemo();